In [97]:
import numpy as np
import pandas as pd

In [98]:
X = np.array([[1,1,1],[1,0,1],[0,1,1],[0,0,1]])
Y = np.array([[0],[1],[1],[0]])

In [99]:
w1 = np.random.randn(3,4)
w3 = np.random.randn(4,1)

b1 = np.random.randn(4,4)
b3 = np.random.randn(4,1)

In [100]:
import math
def sigmoid(x):
    s = 1.0 / (1.0 + np.exp(-1.0*x))
    return s

In [101]:
h1 = sigmoid(np.dot(X,w1) + b1)
output = np.dot(h1,w3) + b3

In [102]:
output

array([[ 0.83916856],
       [-0.10994185],
       [ 0.36481286],
       [ 0.48601677]])

In [103]:
def derivative(output):
    return output * (1.0 - output)
for _ in range(0,100):
    dout=sigmoid(output)*(1-sigmoid(output))    
    w1=w1-dw
    h1 = sigmoid(np.dot(X,w1) + b1)
    output = np.dot(h1,w3) + b3
output

array([[ 0.84534726],
       [-0.10271385],
       [ 0.36825086],
       [ 0.4889386 ]])

In [104]:
error = (Y - output) * derivative(output)

In [105]:
epochs = 2000

w01 = np.random.random((len(X[0]), 5))
w12 = np.random.random((5, 1))

for _ in range(epochs):
    z_h = np.dot(X, w1)
    a_h = sigmoid(z_h)

    z_o = np.dot(a_h, w3)
    a_o = sigmoid(z_o)

    a_o_error = ((1 / 2) * (np.power((a_o - Y), 2)))

    delta_a_o_error = a_o - Y
    delta_z_o = sigmoid(a_o)
    delta_w3 = a_h
    delta_output_layer = np.dot(delta_w3.T,(delta_a_o_error * delta_z_o))

    delta_a_h = np.dot(delta_a_o_error * delta_z_o, w3.T)
    delta_z_h = sigmoid(a_h)
    delta_w1 = X
    delta_hidden_layer = np.dot(delta_w1.T, delta_a_h * delta_z_h)

    w1 = w1 - delta_hidden_layer
    w3 = w3 - delta_output_layer

In [106]:
a_o

array([[ 0.01136969],
       [ 0.99184309],
       [ 0.9918706 ],
       [ 0.01012364]])